# Generated by Django 3.1.7 on 2021-04-16 03:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=10, unique=True)),
                ('description', models.CharField(max_length=3000)),
                ('fullName', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='StockVWAPData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('interval', models.CharField(max_length=10)),
                ('VWAP', models.DecimalField(decimal_places=2, max_digits=7)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.stock')),
            ],
        ),
        migrations.CreateModel(
            name='StockSMAData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('interval', models.CharField(max_length=10)),
                ('SMA', models.DecimalField(decimal_places=2, max_digits=7)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.stock')),
            ],
        ),
        migrations.CreateModel(
            name='StockRSIData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('interval', models.CharField(max_length=10)),
                ('RSI', models.DecimalField(decimal_places=2, max_digits=7)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.stock')),
            ],
        ),
        migrations.CreateModel(
            name='StockDailyData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('interval', models.CharField(max_length=10)),
                ('open', models.DecimalField(decimal_places=2, max_digits=7)),
                ('high', models.DecimalField(decimal_places=2, max_digits=7)),
                ('low', models.DecimalField(decimal_places=2, max_digits=7)),
                ('close', models.DecimalField(decimal_places=2, max_digits=7)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.stock')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phoneNumber', models.CharField(blank=True, max_length=12)),
                ('investmentType', models.IntegerField(choices=[(0, 'LOWRISK'), (1, 'HIGHRISK')], default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FavStock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.stock')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watchlist', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
